### ISSUE TITLE
如何将隐藏界面恢复。

### ISSUE THREAD

**Issue by beforesun** [loveminimal/obsidian-theme-virgo#1]
很喜欢你设计的OB的主题，简洁明了，甚得我心！
我不会CSS，如果我想把隐藏的各界面恢复该怎么操作呢？
或者，我通过组合键实现“一键切换”隐藏与否。
谢谢您的指导。

**Comment by loveminimal** [comment]
因为这款主题是纯 CSS 的，所以没有办法进行交互。😅

官方主题只允许使用特定的字体，不支持三方字体的引入，所以就没有再上传主题仓库了。

如果感觉这个隐藏的视图过于激进了，可以试一下 https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow ，主题仓库直接搜索 [Mado Miniflow](https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow) 即可，它只隐藏了一些不必要元素。

**Comment by loveminimal** [comment]
> 很喜欢你设计的OB的主题，简洁明了，甚得我心！ 我不会CSS，如果我想把隐藏的各界面恢复该怎么操作呢？ 或者，我通过组合键实现“一键切换”隐藏与否。 谢谢您的指导。

因为这款主题是纯 CSS 的，所以没有办法进行交互。😅

官方主题只允许使用特定的字体，不支持三方字体的引入，所以就没有再上传主题仓库了。

如果感觉该主题隐藏的视图过于激进了，可以试一下 https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow ，主题仓库直接搜索 [Mado Miniflow](https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow) 即可，它只隐藏了一些不必要元素。

**Comment by beforesun** [comment]
试过您推荐的Mado Miniflow主题
不过还是喜欢你这个
请提示看从哪里下手
我尝试来自行修改恢复那些隐藏的界面
谢谢

**Comment by loveminimal** [comment]
> 试过您推荐的Mado Miniflow主题 不过还是喜欢你这个 请提示看从哪里下手 我尝试来自行修改恢复那些隐藏的界面 谢谢

![Snipaste_2023-10-07_15-27-46](https://github.com/loveminimal/obsidian-theme-virgo/assets/23427211/667c506b-8ab3-4984-9f30-cf5b342644c8)

这是源码文件，因为是使用的 `theme.scss` 文件，修改源码后就需要重新转译成 `theme.css` 才能生效，你可能需要了解一些 scss 转 css 方面的操作才可以。

或者，你想改成什么样的初始透明度，我可以打包一份给你。

**Comment by beforesun** [comment]
谢谢您，我会了。
